### ISSUE TITLE
Survival Dataset | 2018Q2

### ISSUE THREAD

**Issue by lmwaniki** [chap-uzima/DataWarehouse#4]
Kindly provide CHAP UZIMA data for survivor analysis (as of 31st March 2018) for the upcoming quarterly presentations to CDC.

**Comment by chris-githu** [comment]
Hi @lmwaniki 
Please review these data elements and let me know if there are any we can drop.


Data Element | Notes
-- | --
FacilityName |  
PatientID |  
PatientSource |  
Gender |  
DOB |  
DateOfHIVDiagnosis |  
MaritalStatus |  
RegistrationDate | Between 2004/01/01 and 2018/03/31
ARTStartDate |  
TransferInOnART |  
StartRegimen |  
ARTStatus |  
eCD4 |  
eWHO |  
bCD4 |  
bWHO |  
InitialVL |  
InitialVLDate |  
LastVL |  
LastVLDate |  
ExitReason |  
ExitDate |  
PreARTLastStatus |  
PreARTLastStatusDate |  
LastStatus |  
LastStatusDate |  
eTB |  
eCrypto |  
ePCP |  
eOC |  
eEOC |  
eKS |  
eOtherOI |  
eAnyOI |  
bTB |  
bCrypto |  
bPCP |  
bOC |  
bEOC |  
bKS |  
bOtherOI |  
bAnyOI |  
m6TB |  
m6Crypto |  
m6PCP |  
m6OC |  
m6EOC |  
m6KS |  
m6OtherOI |  
m6AnyOI |  
SwitchedToSecondLine |  
DateOfSwitchToSecondLine |  
ReasonForSwitch |  
LastRegimen |  
LastRegimenLine |  
LastARTDate |  
LastVisit |  
ExpectedReturn |

**Comment by lmwaniki** [comment]
Hi Chris,
The below variables can be dropped from the list. 

MaritalStatus
eCD4 | eWHO | bCD4 | bWHO | InitialVL | InitialVLDate | LastVL | LastVLDate
eTB | eCrypto | ePCP | eOC | eEOC | eKS | eOtherOI | eAnyOI | bTB | bCrypto | bPCP | bOC | bEOC | bKS | bOtherOI | bAnyOI | m6TB | m6Crypto | m6PCP | m6OC | m6EOC | m6KS | m6OtherOI | m6AnyOI | 

Lawrence

**Comment by chris-githu** [comment]
Data Element | Notes
-- | --
FacilityName |  
PatientID |  
PatientSource |  
Gender |  
DOB |  
DateOfHIVDiagnosis |  
MaritalStatus |  
RegistrationDate |  
ARTStartDate |  
TransferInOnART | YES/NO
StartRegimen | ART/PreART
ARTStatus |  
ExitReason |  
ExitDate |  
PreARTLastStatus | StartedART/Lost/Dead/Transfer
PreARTLastStatusDate |  
LastStatus | NULL(Active)/Dead/Lost/Transfer
LastStatusDate |  
SwitchedToSecondLine |  
DateOfSwitchToSecondLine |  
ReasonForSwitch |  
LastRegimen |  
LastRegimenLine |  
LastARTDate |  
LastVisit |  
ExpectedReturn |  

FYI @lmwaniki

**Comment by lmwaniki** [comment]
Looks good @chris-githu

**Comment by lmwaniki** [comment]
@chris-githu 
Data well received
